name: py310_pt200
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - anndata==0.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chex==0.1.7
      - click==8.1.8
      - cmake==3.31.6
      - comm==0.2.2
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - dm-tree==0.1.9
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - etils==1.12.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.17.0
      - flax==0.6.11
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - grpcio==1.70.0
      - h5py==3.13.0
      - idna==3.10
      - igraph==0.11.8
      - importlib-resources==6.5.2
      - ipython==8.33.0
      - ipywidgets==8.1.5
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - leidenalg==0.10.2
      - lightning-utilities==0.13.1
      - lit==18.1.8
      - llvmlite==0.41.1
      - loompy==3.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.2.3
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.58.1
      - numpy==1.23.5
      - numpy-groupies==0.11.2
      - numpyro==0.12.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.1
      - orbax-checkpoint==0.5.16
      - pandas==1.5.3
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - pip==24.0
      - platformdirs==4.3.6
      - plotly==5.10.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==6.30.0
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pydeprecate==0.3.2
      - pymde==0.1.18
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==1.7.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - requests==2.32.3
      - rich==13.9.4
      - scanpy==1.9.6
      - scikit-learn==1.6.1
      - scikit-misc==0.2.0
      - scipy==1.8.0
      - scvelo==0.2.5
      - scvi-tools==0.19.0
      - seaborn==0.13.2
      - session-info==1.0.0
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.3
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.72
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchmetrics==0.11.4
      - torchsde==0.2.6
      - torchvision==0.15.1
      - tqdm==4.67.1
      - trampoline==0.1.2
      - triton==2.0.0
      - tslearn==0.5.3.2
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - velvetvae==0.1.dev0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - yarl==1.18.3
      - zipp==3.21.0
