name: py39_pt250
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.1
  - cuda-cccl_linux-64=12.4.127
  - cuda-crt-dev_linux-64=12.4.131
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-driver-dev_linux-64=12.4.127
  - cuda-nvcc=12.4.131
  - cuda-nvcc-dev_linux-64=12.4.131
  - cuda-nvcc-impl=12.4.131
  - cuda-nvcc-tools=12.4.131
  - cuda-nvcc_linux-64=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvvm-dev_linux-64=12.4.131
  - cuda-nvvm-impl=12.4.131
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.2
  - jupyter_client=6.1.12
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=4.18.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - matplotlib-inline=0.1.2
  - ncurses=6.4
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.9.23
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sysroot_linux-64=2.28
  - tk=8.6.14
  - tornado=6.5
  - traitlets=5.14.3
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - anndata==0.10.8
      - array-api-compat==1.11.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bson==0.5.10
      - chex==0.1.89
      - click==8.1.8
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - docrep==0.3.2
      - etils==1.5.2
      - exceptiongroup==1.3.0
      - filelock==3.13.1
      - flax==0.8.5
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - get-annotations==0.1.2
      - h5py==3.14.0
      - hnswlib==0.8.0
      - humanize==4.12.3
      - idna==3.10
      - igraph==0.11.9
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipywidgets==8.1.7
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.4
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - loompy==3.0.8
      - louvain==0.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mudata==0.2.4
      - multidict==6.6.3
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.3
      - numpy-groupies==0.11.3
      - numpyro==0.18.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - packaging==25.0
      - pandas==2.3.1
      - patsy==1.0.1
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pybind11==3.0.0
      - pygments==2.13.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - python-igraph==0.11.9
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - rich==14.0.0
      - scanpy==1.10.3
      - scikit-learn==1.1.3
      - scipy==1.13.1
      - scvelo==0.3.1
      - scvi-tools==1.1.6.post2
      - seaborn==0.13.2
      - session-info==1.0.1
      - six==1.17.0
      - statsmodels==0.14.5
      - stdlib-list==0.11.1
      - sympy==1.13.1
      - tensorstore==0.1.69
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tivelo==0.1.4
      - toolz==1.0.0
      - torch==2.5.0+cu121
      - torchaudio==2.5.0+cu121
      - torchmetrics==1.7.4
      - torchvision==0.20.0+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - widgetsnbextension==4.0.14
      - yarl==1.20.1
      - zipp==3.23.0
