name: py310_pt260
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.34.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - anndata==0.11.4
      - array-api-compat==1.11.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - click==8.1.8
      - cmake==3.31.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - docrep==0.3.2
      - etils==1.12.2
      - filelock==3.18.0
      - flax==0.10.4
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - humanize==4.12.2
      - idna==3.10
      - importlib-resources==6.5.2
      - jax==0.4.35
      - jaxlib==0.4.35
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - lit==18.1.8
      - llvmlite==0.44.0
      - loompy==3.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.2.0
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - numpy-groupies==0.11.2
      - numpyro==0.18.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.5
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.1.0
      - propcache==0.3.1
      - protobuf==6.30.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - scanpy==1.11.0
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - scvelo==0.3.3
      - scvi-tools==1.3.0
      - seaborn==0.13.2
      - session-info2==0.1.2
      - simplejson==3.20.1
      - sparse==0.15.5
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.72
      - threadpoolctl==3.6.0
      - toolz==1.0.0
      - torch==2.6.0
      - torchaudio==2.0.2
      - torchdiffeq==0.2.5
      - torchmetrics==1.7.0
      - torchvision==0.15.2
      - tqdm==4.67.1
      - treescope==0.1.9
      - triton==3.2.0
      - typing-extensions==4.13.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - velovi==0.4.0
      - werkzeug==3.1.3
      - xarray==2025.3.0
      - yarl==1.18.3
      - zipp==3.21.0
