name: py39_pt111
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bokeh=3.4.3
  - bottleneck=1.4.2
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - cytoolz=1.0.1
  - dask-core=2022.2.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - freetype=2.12.1
  - heapdict=1.0.1
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - msgpack-python=1.0.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - packaging=24.2
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.9.0
  - python-dateutil=2.9.0.post0
  - python-lmdb=1.6.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - six=1.17.0
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - adjusttext==0.7.3
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - anndata==0.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - bezier==2021.2.12
      - cell2fate==0.1a0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chex==0.1.7
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - colorcet==3.1.0
      - commonmark==0.9.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dask==2024.8.0
      - datashader==0.14.0
      - datashape==0.5.2
      - dgl==0.6.1
      - distributed==2024.8.0
      - dm-tree==0.1.8
      - docrep==0.3.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.13.1
      - flax==0.7.4
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - future==1.0.0
      - grpcio==1.70.0
      - gseapy==1.1.5
      - h5py==3.13.0
      - hnswlib==0.6.2
      - idna==3.10
      - igraph==0.10.8
      - importlib-metadata==4.8.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jax==0.4.10
      - jaxlib==0.4.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - leidenalg==0.10.1
      - lightning-utilities==0.12.0
      - lit==15.0.7
      - llvmlite==0.43.0
      - loompy==3.0.8
      - lz4==4.4.3
      - markdown==3.7
      - matplotlib==3.5.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.23.5
      - numpy-groupies==0.11.2
      - numpyro==0.12.1
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.1
      - orbax-checkpoint==0.4.4
      - pandas==1.4.2
      - param==2.2.0
      - patsy==1.0.1
      - propcache==0.3.0
      - protobuf==5.29.3
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pyct==0.5.0
      - pydeprecate==0.3.1
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pytorch-lightning==1.5.10.post0
      - pytz==2025.1
      - requests==2.32.3
      - rich==12.3.0
      - scanpy==1.9.1
      - scikit-learn==1.6.1
      - scipy==1.8.0
      - scvelo==0.2.4
      - scvi-tools==0.16.1
      - seaborn==0.11.2
      - session-info==1.0.0
      - setuptools==59.5.0
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.1
      - tbb==2022.0.0
      - tblib==3.0.0
      - tcmlib==1.2.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.45
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - torch==1.11.0+cu113
      - torchaudio==0.11.0+cu113
      - torchmetrics==0.7.0
      - torchvision==0.12.0+cu113
      - tqdm==4.67.1
      - triton==2.0.0
      - tzdata==2025.1
      - umap-learn==0.5.4
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xyzservices==2025.1.0
      - yarl==1.18.3
      - zipp==3.21.0
