name: py310_pt212
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - cudatoolkit=11.8.0
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=1.1.1w
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - anndata==0.10.7
      - annotated-types==0.7.0
      - anyio==4.8.0
      - anysqlite==0.0.5
      - array-api-compat==1.10.0
      - arrow==1.3.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - babel==2.17.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.13.3
      - biothings-client==0.4.1
      - blessed==1.20.0
      - boto3==1.37.3
      - botocore==1.37.3
      - build==1.2.2.post1
      - cachecontrol==0.14.2
      - cellrank==2.0.7
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - chex==0.1.7
      - cleo==2.1.0
      - click==8.1.8
      - colorcet==3.1.0
      - contourpy==1.3.1
      - crashtest==0.4.1
      - croniter==1.4.1
      - cryptography==44.0.1
      - cycler==0.12.1
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - distlib==0.3.9
      - dm-tree==0.1.9
      - docrep==0.3.2
      - docutils==0.21.2
      - dulwich==0.22.7
      - dunamai==1.23.0
      - dynamo-release==1.4.2rc1
      - editor==1.6.6
      - et-xmlfile==2.0.0
      - etils==1.12.0
      - fastapi==0.115.9
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - findpython==0.6.2
      - flax==0.10.4
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - future==1.0.0
      - get-version==3.5.5
      - graphvelo==0.1.9
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.13.0
      - hishel==0.1.3
      - hnswlib==0.8.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - humanize==4.12.1
      - identify==2.6.8
      - idna==3.10
      - igraph==0.11.8
      - imagesize==1.4.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - inquirer==3.4.0
      - installer==0.7.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jax==0.5.1
      - jaxlib==0.5.1
      - jeepney==0.8.0
      - jinja2==3.0.3
      - jmespath==1.0.1
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - latentvelo==0.1
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.0.9.post0
      - lightning-cloud==0.5.70
      - lightning-utilities==0.12.0
      - llvmlite==0.44.0
      - loess==2.1.2
      - loompy==3.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.2.3
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - natsort==8.4.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numba==0.61.0
      - numdifftools==0.9.41
      - numpy==1.26.0
      - numpy-groupies==0.11.2
      - numpyro==0.17.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.1
      - orbax-checkpoint==0.11.6
      - ordered-set==4.1.0
      - pandas==2.2.3
      - pathlib==1.0.1
      - patsy==1.0.1
      - pbs-installer==2025.2.12
      - pillow==11.1.0
      - pkginfo==1.12.1.2
      - plotbin==3.1.7
      - plotly==5.10.0
      - poetry==2.1.1
      - poetry-core==2.1.1
      - pre-commit==4.1.0
      - progressbar2==4.5.0
      - propcache==0.3.0
      - protobuf==5.29.3
      - pycparser==2.22
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pydeprecate==0.3.1
      - pyg-lib==0.3.1+pt21cu118
      - pygam==0.10.1
      - pygpcca==1.0.4
      - pyjwt==2.10.1
      - pymde==0.1.18
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyproject-hooks==1.2.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-igraph==0.11.8
      - python-multipart==0.0.20
      - python-utils==3.9.1
      - pytorch-lightning==1.5.10.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - rapidfuzz==3.12.1
      - readchar==4.2.1
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - runs==1.2.2
      - s3transfer==0.11.3
      - scanpy==1.11.0
      - scikit-learn==1.4.2
      - scikit-misc==0.2.0
      - scipy==1.15.2
      - scvelo==0.3.3
      - scvi-tools==1.0.0
      - sdevelo==0.2.12
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - session-info==1.0.0
      - session-info2==0.1.2
      - setuptools==59.5.0
      - shellingham==1.5.4
      - simplejson==3.20.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sparse==0.15.5
      - sphinx==8.1.3
      - sphinx-autodoc-typehints==3.0.1
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.45.3
      - starsessions==1.3.0
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.72
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.1.2+cu118
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchaudio==2.1.2+cu118
      - torchdiffeq==0.2.5
      - torchmetrics==1.6.1
      - torchsde==0.2.6
      - torchvision==0.16.2+cu118
      - tqdm==4.62.3
      - trampoline==0.1.2
      - treescope==0.1.9
      - triton==2.1.0
      - trove-classifiers==2025.2.18.16
      - tslearn==0.5.3.2
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - veloae==0.2.0
      - velocytoanalysis==1.1.0
      - velovae==0.1.3b0
      - velovi==0.3.1
      - velvetvae==0.1.dev0
      - virtualenv==20.29.2
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xarray==2025.1.2
      - xmod==1.8.1
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0

