name: py311_pt221
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - adjusttext==1.3.0
      - adlfs==2024.12.0
      - aiobotocore==2.21.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - alembic==1.15.2
      - anndata==0.11.4
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - appdirs==1.4.4
      - array-api-compat==1.11.2
      - arviz==0.21.0
      - astropy==7.0.1
      - astropy-iers-data==0.2025.4.14.0.37.22
      - atpublic==5.1
      - attrs==25.3.0
      - azure-core==1.33.0
      - azure-datalake-store==0.0.53
      - azure-identity==1.21.0
      - azure-storage-blob==12.25.1
      - babel==2.17.0
      - backports-tarfile==1.2.0
      - beartype==0.18.5
      - beautifulsoup4==4.13.4
      - black==25.1.0
      - bleach==6.2.0
      - blinker==1.9.0
      - botocore==1.37.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - contourpy==1.3.2
      - croniter==6.0.0
      - cryptography==44.0.2
      - cycler==0.12.1
      - daft==0.4.10
      - databricks-sdk==0.50.0
      - dataclasses-json==0.5.9
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diffrax==0.7.0
      - diskcache==5.6.3
      - docker==7.1.0
      - docrep==0.3.2
      - docstring-parser==0.16
      - docutils==0.21.2
      - duckdb==1.2.2
      - dulwich==0.22.8
      - einops==0.8.1
      - entrypoints==0.4
      - equinox==0.12.1
      - etils==1.12.2
      - executing==2.2.0
      - expression==5.6.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.1.0
      - flax==0.10.5
      - flyteidl==1.15.1
      - flytekit==1.15.3
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gcsfs==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-api-python-client==2.167.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.0
      - griffe==1.7.2
      - grpcio==1.68.0
      - grpcio-status==1.68.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - h5netcdf==1.6.1
      - h5py==3.13.0
      - httpcore==1.0.8
      - httplib2==0.22.0
      - httpx==0.28.1
      - humanize==4.12.2
      - hydra-core==1.3.2
      - hydra-zen==0.14.0
      - ibis-framework==10.4.0
      - idna==3.10
      - igraph==0.11.8
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - ipywidgets==8.1.6
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jax==0.5.3
      - jaxlib==0.5.3
      - jaxtyping==0.3.1
      - jeepney==0.9.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpickle==4.0.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.14
      - jupytext==1.17.0
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.1.4
      - lightning-utilities==0.14.3
      - lineax==0.0.8
      - llvmlite==0.44.0
      - loompy==3.0.8
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - marshmallow-enum==1.5.1
      - marshmallow-jsonschema==0.13.0
      - mashumaro==3.15
      - matplotlib==3.9.1
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - mlflow==2.21.3
      - mlflow-skinny==2.21.3
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msal==1.32.0
      - msal-extensions==1.3.1
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.4.3
      - multipledispatch==1.0.0
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.2
      - numpy-groupies==0.11.2
      - numpyro==0.18.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opentelemetry-api==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optimistix==0.0.10
      - orbax-checkpoint==0.11.12
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - parsy==2.1
      - pathspec==0.12.1
      - patsy==1.0.1
      - pillow==11.2.1
      - plum-dispatch==2.5.7
      - plumbum==1.9.0
      - polars==1.27.1
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - protoc-gen-openapiv2==0.0.1
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyerfa==2.0.1.5
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pyrovelocity==0.3.0b2
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - pytimeparse==1.1.8
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - quartodoc==0.9.1
      - referencing==0.36.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - returns==0.23.0
      - rich==14.0.0
      - rich-click==1.8.8
      - roman-numerals-py==3.1.0
      - rpds-py==0.24.0
      - rsa==4.9.1
      - s3fs==2025.3.2
      - scanpy==1.11.1
      - scikit-learn==1.5.2
      - scipy==1.13.0
      - scvelo==0.3.2
      - scvi-tools==1.1.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - session-info2==0.1.2
      - simplejson==3.20.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sparse==0.16.0
      - sphinx==8.2.3
      - sphinx-markdown-builder==0.6.8
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sphobjinv==2.3.1.2
      - sqlalchemy==2.0.40
      - sqlglot==26.14.0
      - sqlparse==0.5.3
      - starlette==0.46.2
      - statsd==4.0.1
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.73
      - termcolor==3.0.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchmetrics==1.7.1
      - torchvision==0.17.1
      - tqdm==4.67.1
      - treescope==0.1.9
      - trio==0.29.0
      - triton==2.2.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - uvicorn==0.34.1
      - validators==0.34.0
      - wadler-lindig==0.1.5
      - watchdog==6.0.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xarray==2025.3.1
      - xarray-einstats==0.8.0
      - yarl==1.19.0
      - zstandard==0.23.0

