name: py39_pt113
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - ca-certificates=2025.2.25
  - comm=0.2.1
  - cudatoolkit=10.2.89
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - adjusttext==0.7.3
      - anndata==0.10.9
      - array-api-compat==1.11.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cycler==0.12.1
      - deepvelo==0.2.8
      - dgl==0.9.1
      - exceptiongroup==1.3.0
      - fonttools==4.58.0
      - get-annotations==0.1.2
      - h5py==3.13.0
      - hnswlib==0.6.2
      - idna==3.10
      - igraph==0.9.11
      - ipywidgets==8.1.7
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - loompy==3.0.8
      - matplotlib==3.5.3
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.23.5
      - numpy-groupies==0.11.3
      - packaging==25.0
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.2.1
      - portalocker==3.1.1
      - psutil==7.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytz==2025.2
      - requests==2.32.3
      - scanpy==1.9.6
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scvelo==0.2.5
      - seaborn==0.11.2
      - session-info==1.0.1
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - tbb==2022.1.0
      - tcmlib==1.3.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+cu116
      - torchdata==0.5.1
      - torchvision==0.14.1+cu116
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - umap-learn==0.5.4
      - urllib3==2.4.0
      - widgetsnbextension==4.0.14
